# Generated by Django 4.1.8 on 2023-10-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uploaded_Voter_Slip', models.ImageField(max_length=1000, upload_to='')),
            ],
            options={
                'db_table': 'folder_path',
            },
        ),
    ]
