# Generated by Django 4.1.13 on 2023-11-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('emailid', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.CharField(max_length=13, unique=True)),
                ('constituency', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=80)),
                ('mandal', models.CharField(max_length=100)),
                ('pollingstation', models.CharField(max_length=100)),
                ('pollingstationnumber', models.CharField(max_length=100)),
            ],
        ),
    ]
