# Generated by Django 4.1.13 on 2024-02-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=12)),
                ('lastname', models.CharField(max_length=25)),
                ('Email_id', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=56, unique=True)),
                ('phonenumber', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Registration',
            },
        ),
    ]
