# Generated by Django 4.1 on 2022-09-05 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='many',
            fields=[
                ('username', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=52)),
                ('contact', models.CharField(max_length=52)),
            ],
        ),
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=65)),
                ('many', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='many.many')),
            ],
        ),
    ]
