# Generated by Django 4.1 on 2022-09-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=18)),
                ('email', models.CharField(max_length=66)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
